### ISSUE TITLE
QOL recommendations 

### ISSUE THREAD

**Issue by cyberdrop-me** [lambwheit/CyberdropDownloader#1]
Nice tool

I recommend downloaders grab the download link from id="file" as it can go full speed. The clickable link onsite (class="image") has a bandwidth rate limit. (the fast link has a `/s/` inbetween the filename and domain name)
https://github.com/lambwheit/CyberdropDownloader/blob/a12dba642e2831eca68985dc1945c6a2c08d9c81/CyberdropDownloader/Program.cs#L99

You can also get the full original filename in the elements title attributes instead of parsing the download link 
https://github.com/lambwheit/CyberdropDownloader/blob/a12dba642e2831eca68985dc1945c6a2c08d9c81/CyberdropDownloader/Program.cs#L121-L129

Whats this about
https://github.com/lambwheit/CyberdropDownloader/blob/a12dba642e2831eca68985dc1945c6a2c08d9c81/CyberdropDownloader/Program.cs#L131-L132

**Comment by lambwheit** [comment]
oh i was trying something out with webrequests, forgot to remove will add the abv improvements

**Comment by lambwheit** [comment]
did the filename like abv as if i want to do it through the title attribute i have to get all names through a regex 1st then add it to a list, which isnt very practical. Changed regex to use id="file" instead of class="image"
